apiVersion: v1
kind: PersistentVolume
metadata:
  name: itsf-persistent-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/c/Users/polom/Documents/Pro/Tests/Kubernetes/risf/itsf/volume"