apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: itsf-persistent-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10M