apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-itsf
  labels:
    app: nginx-itsf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-itsf
  template:
    metadata:
      labels:
        app: nginx-itsf
    spec:
      volumes:
        - name: itsf-persistent-volume
          persistentVolumeClaim:
            claimName: itsf-persistent-volume-claim
      containers:
        - name: nginx-itsf
          image: nginxinc/nginx-unprivileged:1.23-alpine
          securityContext:
            runAsUser: 101
            runAsGroup: 101
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - all
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: itsf-persistent-volume