apiVersion: v1
kind: Service
metadata:
  name: itsf-nginx-service
spec:
  selector:
    app: nginx-itsf
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 80
      nodePort: 30002