apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-risf
  labels:
    app: nginx-risf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-risf
  template:
    metadata:
      labels:
        app: nginx-risf
    spec:
      containers:
        - name: nginx-risf
          image: elpolo/risf-nginx
          ports:
            - containerPort: 80