apiVersion: v1
kind: Service
metadata:
  name: risf-nginx-service
spec:
  selector:
    app: nginx-risf
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
      nodePort: 30001