apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-risf
  labels:
    app: nginx-risf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-risf
  template:
    metadata:
      labels:
        app: nginx-risf
    spec:
      containers:
        - name: nginx-risf
          image: elpolo/risf-nginx:2-noroot
          imagePullPolicy: Always
          securityContext:
            runAsUser: 101
            runAsGroup: 101
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - all
          ports:
            - containerPort: 8080